# Generated by Django 6.1.1 on 2026-09-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_publisher_article_newsletter_user_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('approve_article', 'Can approve articles')]},
        ),
    ]
