# Generated by Django 6.1.1 on 2026-09-21 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsletter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'journalist'}, related_name='journalist_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_readers', to='news.publisher'),
        ),
    ]
