# Generated by Django 6.1.1 on 2026-09-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_options_publisher_editors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={},
        ),
    ]
